### ISSUE TITLE
3.a Cholesky Issue

### ISSUE THREAD

**Issue by aumashankar8** [utexas-edp-380C-28/Fa22-Lab3-aumashankar8#2]
Hello, I'm having a bit of trouble with implementing the rmvnorm script. It's giving me this error when I run it:

Error in chol.default(Sigma) : 
the leading minor of order 2 is not positive definite

It looks like my correlation matrix can't be decomposed? This from line 135 - 156 for reference.

@bkeller2

**Comment by bkeller2** [comment]
@aumashankar8 

Look at the following line:
https://github.com/utexas-edp-380C-28/Fa22-Lab3-aumashankar8/blob/fe09c5bf4533c67fe8e4e7ab4c6939fa0accd57f/EDP-380C-28-R2-Lab3.R#L146

This is the covariance matrix that results from it:
```r
setupParam$sigmaX
#     [,1] [,2]
#[1,]  1.0  2.0
#[2,]  0.6  1.2
```

This error is because you have created an impossible covariance matrix.

**Comment by aumashankar8** [comment]
I figured it out. My rho matrix wasn't setup correctly. Thought I had checked it but it turns out I did not. Thank you!
